<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-TMDKBPI" failures="1" tests="6" name="com.indigo.mainscript.TestOne" time="169.547" errors="0" timestamp="30 Apr 2020 23:33:15 GMT" skipped="4">
  <testcase classname="com.indigo.mainscript.TestOne" name="flightPrice_2" time="35.800">
    <skipped/>
  </testcase> <!-- flightPrice_2 -->
  <testcase classname="com.indigo.mainscript.TestOne" name="flightPrice_1" time="35.925"/>
  <testcase classname="com.indigo.mainscript.TestOne" name="flightPrice_2" time="32.115">
    <failure message="expected [₹1,967] but found [₹1,966]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [₹1,967] but found [₹1,966]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.indigo.testcases.TestTwo.tco2(TestTwo.java:61)
at com.indigo.mainscript.TestOne.flightPrice_2(TestOne.java:44)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
    </failure>
  </testcase> <!-- flightPrice_2 -->
  <testcase classname="com.indigo.mainscript.TestOne" name="flightPrice_2" time="33.476">
    <skipped/>
  </testcase> <!-- flightPrice_2 -->
  <testcase classname="com.indigo.mainscript.TestOne" name="flightPrice_2" time="32.231">
    <skipped/>
  </testcase> <!-- flightPrice_2 -->
  <testcase classname="com.indigo.mainscript.TestOne" name="Testtwo">
    <skipped/>
  </testcase> <!-- Testtwo -->
</testsuite> <!-- com.indigo.mainscript.TestOne -->
